### ISSUE TITLE
Wrong tuple deserialization.

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge.Newtonsoft.Json#125] opened 2018-06-20 19:25 UTC
https://deck.net/6609455a8a965683cf5ae4381c96db65

```C#
public class App
{
    public static void Main()
    {
            string json = "{ \"item1\": \"test1\", \"item2\": \"test2\" }";

            (string Prop1, string Prop2) val = ((string Test1, string Test2))JsonConvert.DeserializeObject(json, typeof((string Test1, string Test2)));
		
            Console.WriteLine(val.Prop1 ?? "null");
            Console.WriteLine(val.Prop2 ?? "null");
    }
}
```

**Expected:**
![image](https://user-images.githubusercontent.com/4306334/41680035-c557612c-74d8-11e8-8b28-b570d6d20f54.png)

**Actual:**
![image](https://user-images.githubusercontent.com/4306334/41680015-b99362a0-74d8-11e8-9399-8e6a63dbdd41.png)

**Comment by vladsch** [comment] 2018-06-20 19:33
Hi,

Why do you use lower case for keys? If serialize value tuple object then camel case is used for keys

**Comment by hardhub** [comment] 2018-06-20 19:43
I am not sure what you mean.

lowercase  
camelCase  
PascalCase  

I am using my own ContractResolver which converts member names to camelCase.

So it is item1 and item2 in JSON.

I described case-related question here: https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/issues/14
And of course it is different behavior of JSON.Net. So Bridge.Newtonsoft.Json should work with case as described in 14 issue.

**Comment by hardhub** [comment] 2018-06-20 19:44
Hi Vlad! I do not know if it is OK to say _Hi_ in comments ))

**Comment by vladsch** [comment] 2018-06-26 20:01
Fixed in https://github.com/bridgedotnet/Bridge/pull/3653

**Comment by hardhub** [comment] 2018-06-26 21:11
Thanks @vladsch. Do you think it will be in version 17.2?

**Comment by fabriciomurta** [comment] 2018-07-03 04:58
So, this is pretty much a duplicate of bridgedotnet/Bridge#3653, but as it is not really obvious I'm not sure it's worth marking a duplicate... So as the fix didn't incur any change in this repository, to make it simpler with the cross-repo referencing, I will mark this one as a duplicate. Anyway, the references left in github will be kept.

**Closed by fabriciomurta** 2018-07-03 04:58 UTC
Labels: defect, in-progress, premium

**Comment by fabriciomurta** [comment] 2018-07-03 04:59
Forgot to mention, the issue this "duplicates" is bridgedotnet/Bridge#3649.
